### ISSUE TITLE
[Feature] Way to restore deleted vehicles

### ISSUE THREAD

**Issue by Starystars67** [Starystars67/BeamNG-MP#462] opened 2023-12-21 15:49 UTC
Presently the only way to restore a deleted vehicle is to have the owning player respawn the vehicle.
This is not ideal and a way to maintain the vehicles in memory so they can be brought back would be nice to have.

Open to suggestions

**Comment by OfficialLambdax** [comment] 2024-01-01 21:16
duplicate of https://github.com/BeamMP/BeamMP/issues/304

**Closed as completed by OfficialLambdax** 2024-01-01 21:16 UTC
Labels: duplicate
