### ISSUE TITLE
Rephrase the LICENSE. Not to be confused with #210

### ISSUE THREAD

**Issue by ghost** [Starystars67/BeamNG-MP#302] opened 2023-01-09 20:38 UTC
**Is your feature request related to a problem? Please describe.**
The current license, the "Custom ISC License," has several issues that may make it difficult for others to use and contribute to the software. The license does not mention "copying and distributing" and includes restrictions on use and modification that may be unclear and potentially non-compliant with open source principles.

**Describe the solution you'd like**
I would like to rephrase the license to address these issues and better align with open source principles. I propose adopting a license that allows users to freely use, modify, and distribute the software, provided that any modified version is shared under the same license.

**Describe alternatives you've considered**
I have thought about using a copyleft license like the GNU General Public License 3.0, as discussed in [issue 210](https://github.com/BeamMP/BeamMP/issues/210).

**Additional context**
My goal is to make the software as widely accessible and easy to use as possible, while still protecting the rights of the authors and ensuring that any contributions are properly credited. I believe that rephrasing the license to be more permissive and clearly outline the terms of use and distribution will help achieve this goal.

**Proposed LICENSE**

```
Custom ISC License

Copyright (c) 2021, BeamMP Mod Team

Permission to use and modify this software is granted, free of charge, provided that the modified version
is shared under the same license and any work is committed upstream.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

**Comment by lionkor** [comment] 2023-01-10 09:01
I do not see how this isn't a duplicate of #210? BeamMP is **not** open source, and we don't aim to be open source, we don't aim to align with open source principles, and we don't aim to allow users to freely modify and then distribute the software. Instead, we aim to keep all of BeamMP's code in the control of the project (the github.com/BeamMP org), to maintain the right to commercialize, to maintain the right to distribute, as discussed in #210. 

> potentially non-compliant with open source principles

No, *deliberately* non-compliant with open source principles.

For now I'll close this as a duplicate, @other maintainers see if you agree. Thanks for your time @shawnjb

**Closed as not planned by lionkor** 2023-01-10 09:01 UTC
Labels: duplicate
