### ISSUE TITLE
Emoji support for imgui chat

### ISSUE THREAD

**Issue by O1LER** [Starystars67/BeamNG-MP#505] opened 2024-01-25 11:27 UTC
Imgui chat does not support emojis. Would be nice if it did. Or at least show some generic symbol, not `???`

**Comment by snepsnepsnep** [comment] 2024-01-25 13:12
Duplicate of https://github.com/BeamMP/BeamMP/issues/477

**Closed as completed** 2024-01-25 13:23 UTC
Labels: duplicate
