### ISSUE TITLE
[Bug] New chat does not expand correctly

### ISSUE THREAD

**Issue by Desoroxxx** [Starystars67/BeamNG-MP#478] opened 2024-01-02 11:39 UTC
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
The new chat does not remember its size previous expanded size, meaning once expanded again you must rescale it to see anything.

**To Reproduce**
1. Click the `^` button to collapse the chat
2. Click the `v` button to expand the chat
3. The chat did not remember its previous size.

**Expected behavior**
The new chat should remember it's previous expanded size, so that once expanded again it can return to its previous size.

**Screenshots**
### Expanded Pre collapse (Normal)
![image](https://github.com/BeamMP/BeamMP/assets/82710983/d61831c4-7553-440c-9414-b6b7f210186e)

### Collapsed (Normal)
![image](https://github.com/BeamMP/BeamMP/assets/82710983/642037a8-5ec4-4ffa-b323-21a5a26e7349)

### Expanded (Not normal)
![image](https://github.com/BeamMP/BeamMP/assets/82710983/cc566f22-ef99-44e6-a206-30a2bca53b7f)

**Desktop:**
 - OS + Version: Windows 11
 
 **Potential fix:**
 ImGui, already has a collapse/expand functionality for every window by default, use that instead.

**Comment by OfficialLambdax** [comment] 2024-01-02 14:16
Duplicate of https://github.com/BeamMP/BeamMP/issues/446

**Closed as completed by OfficialLambdax** 2024-01-02 14:16 UTC
Labels: duplicate
